name: Deploy

on:
  push:
    tags:
      - "v?[0-9]+.[0-9]+.[0-9]+"

jobs:
  Ship-to-TER:
    name: 'Ship to TER'
    runs-on: ubuntu-latest
    env:
      TYPO3_API_TOKEN: ${{ secrets.TYPO3_API_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: intl, mbstring, json, zip, curl
          tools: composer:v2
          coverage: none

      - name: "Extract tag, version from GITHUB_REF"
        id: get-version
        run: |
          echo "version=$(echo $GITHUB_REF | sed -E -n 's#^refs/tags/v?([0-9]+\.)([0-9]+\.)([0-9]+)#\1\2\3#p')" >> $GITHUB_ENV

      - name: Deploy to TER
        run: |
          if [ -n "${{ secrets.TYPO3_API_TOKEN  }}" ]; then
            echo -e "Preparing upload of release ${{ env.version }} to TER\n";
            # Install tailor
            composer global require typo3/tailor --prefer-dist --no-progress
            # Upload
            echo "Uploading release ${{ env.version }} to TER\n"
            php ~/.composer/vendor/bin/tailor ter:publish --comment "https://github.com/DirkPersky/typo3-dp_cookieconsent/releases" ${{ env.version }}
          fi;
